# CI for command line NodeJS Applications
name: nodejs
on:
  push:
     paths:
      - "**/**"
      - "!**/*.md/**"

env:
  CI: true
  FORCE_COLOR: 2
  SKIP_PREFLIGHT_CHECK: true

jobs:
  pipeline:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ['14.x']
        os: ['ubuntu-latest']

    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.5

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node }}
#          cache: 'yarn'

      - name: Install yarn dependencies
        run: yarn install
        id: install

      - name: Run build
        run: yarn run build
        id: build

      - uses: streetsidesoftware/cspell-action@v1.0.1
        with:
          # Github token used to fetch the list of changed files in the commit.
          # Default: ${{ github.token }}
          github_token: ''

          # Define glob patterns to filter the files to be checked. Use a new line between patterns to define multiple patterns.
          # The default is to check ALL files that were changed in in the pull_request or push.
          # Note: `ignorePaths` defined in cspell.json still apply.
          # Example:
          # files: |
          #   **/*.{ts,js}
          #   !dist/**/*.{ts,js}
          #   # Hidden directories need an explicit .* to be included
          #   .*/**/*.yml
          #
          # To not check hidden files, use:
          # files: "**"
          #
          # Default: ALL files
          files: ''

          # The point in the directory tree to start spell checking.
          # Default: .
          root: 'src/'

          # Notification level to use with inline reporting of spelling errors.
          # Allowed values are: warning, error, none
          # Default: warning
          inline: warning
          strict: false